---
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/ban-ts-comment":
    - 0
  eol-last: 2
  keyword-spacing:
    - 0
    - after: true
      overrides:
        catch:
          after: false
        for:
          after: false
        if:
          after: false
        switch:
          after: false
        while:
          after: false
  no-case-declarations: 0
  no-trailing-spaces: 2
  no-var: 2
  quotes:
    - 2
    - double
  semi:
    - 2
    - always
  prefer-const: 2